homeassistant:
  name: My Smart Home
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 216
  unit_system: metric
  time_zone: Europe/Kiev
  customize: !include customize.yaml
  packages: !include_dir_merge_named includes/packages/

frontend:
  themes: !include_dir_merge_named themes

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# Викидання 
group: !include includes/groups.yaml
climate: !include includes/climate.yaml

script: !include scripts.yaml
scene: !include scenes.yaml
automation: !include automations.yaml

switch: !include includes/switch.yaml

recorder: !include includes/recorder.yaml
history: !include includes/history.yaml
logbook: !include includes/logbook.yaml


sensor: !include_dir_merge_list includes/sensor


# IoT
sonoff:
  username: !secret sonoff_account
  password: !secret sonoff_password

# DataBase Influx
influxdb:  
  host: 192.168.0.137
  port: 8086
  database: homeassistant
  username: !secret influx_login
  password: !secret influx_pass
  max_retries: 3
  default_measurement: state

# Polling control Plum EcoNet24 by Plum
rest:
  - authentication: basic
    scan_interval: 60
    username: admin
    password: admin
    resource: "http://192.168.0.101/econet/regParams"
    sensor:
      - name: Температура горілки
        device_class: temperature
        unit_of_measurement: "°C"
        value_template: "{{value_json['curr']['tempFeeder']| round(1)}}"
      - name: Потужність котла
        device_class: energy
        unit_of_measurement: "kWh"
        value_template: "{{value_json['curr']['boilerPowerKW']| round(1)}}"
      - name: Температура котла
        device_class: temperature
        unit_of_measurement: "°C"
        value_template: "{{value_json['curr']['tempCO']| round(1)}}"
      - name: Температура Бойлера Plum
        device_class: temperature
        unit_of_measurement: "°C"
        value_template: "{{value_json['curr']['tempCWU']| round(1)}}"  

telegram_bot: 
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids: 
      - !secret telegram_id

notify:
  - name: telegram_id_1
    platform: telegram
    chat_id: !secret telegram_id

# homekit: !include includes/climate.yaml
# homekit:
#   - filters:
#     include_domains:
#       - light
#     include_entities:
#       - binary_sensor.dveri_golovnii_vkhid

