- platform: template
  switches:
    controls_clime:
      friendly_name: "Controls Clime"
      value_template: "{{ is_state_attr('climate.bilia_kukhni_na_verkhu', 'preset_mode', 'Off') }}"
      turn_on:
        service: script.turn_on
        target:
          entity_id:
            - script.clime_turn_on
      turn_off:
        service: script.turn_off
        target:
          entity_id:
            - script.clime_turn_off
      icon_template: >-
        {% if is_state('controls_clime', 'on') %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}
      